name: "PR Checks"
on: [pull_request, push]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm i -g npm@7

    - name: "npm ci"
      run: npm ci

    - name: "lint"
      run: npx eslint .

    - name: "npm test"
      run: npm test
